### ISSUE TITLE
Benefits are not clear

### ISSUE THREAD

**Issue by displague** [tinkerbell/operator#1]
The root README.md does not discuss what the benefits of this operator are compared to the alternatives. The alternative I have in mind is Helm. 

What are the drawbacks of this operator approach to the Helm approach?

If helm will be needed to install and update this operator does that change the benefits?

**Comment by jacobweinstock** [comment]
great points. I'll start by adding some context here.

There is a good amount of complexity in deploying the whole Tinkerbell stack. The current Helm chart does a pretty good job abstracting that. The initial `helm install` has a pretty good experience, assuming you don't veer too much outside the defaults. The challenge arises when we need to upgrade. If a CRD needs upgraded Helm can apply the new CRDs but it won't migrate and transform the existing CR Objects into the upgraded one. 

Also, the Tinkerbell chart tried to use Helm [Chart hooks](https://helm.sh/docs/topics/charts_hooks/) and hook-weights and ran into issue to get them working properly. An operator like this would allow us to handle ordering properly. 

Another one, different versions of Tinkerbell stack services need to be handled properly for the whole stack to work correctly. We don't have any docs that speak to this and even if we did it would be left up to the consumer to properly handle them. This controller would/will have this knowledge built in and thus improving the maintainability/use-ability of the stack. 

Finally, I personally take inspiration from the [cilium cli](https://github.com/cilium/cilium-cli) tool. While this repo would not be an equivalent cli, it sets us up to be able to build one on top of this repo.

I'll ping @moadqassem and @chrisdoherty4 to add others.

**Comment by moadqassem** [comment]
> great points. I'll start by adding some context here.
> 
> 
> 
> There is a good amount of complexity in deploying the whole Tinkerbell stack. The current Helm chart does a pretty good job abstracting that. The initial `helm install` has a pretty good experience, assuming you don't veer too much outside the defaults. The challenge arises when we need to upgrade. If a CRD needs upgraded Helm can apply the new CRDs but it won't migrate and transform the existing CR Objects into the upgraded one. 
> 
> 
> 
> Also, the Tinkerbell chart tried to use Helm [Chart hooks](https://helm.sh/docs/topics/charts_hooks/) and hook-weights and ran into issue to get them working properly. An operator like this would allow us to handle ordering properly. 
> 
> 
> 
> Another one, different versions of Tinkerbell stack services need to be handled properly for the whole stack to work correctly. We don't have any docs that speak to this and even if we did it would be left up to the consumer to properly handle them. This controller would/will have this knowledge built in and thus improving the maintainability/use-ability of the stack. 
> 
> 
> 
> Finally, I personally take inspiration from the [cilium cli](https://github.com/cilium/cilium-cli) tool. While this repo would not be an equivalent cli, it sets us up to be able to build one on top of this repo.
> 
> 
> 
> I'll ping @moadqassem and @chrisdoherty4 to add others.

I would create a new section in the readme file which explains the motivation behind it and would use what @jacobweinstock has summarized here and some other points to it.

**Comment by moadqassem** [comment]
Alright, so based on what we have discussed in the previous comments, here are some of our thoughts summarised in this PR https://github.com/moadqassem/kubetink/pull/3
