### ISSUE TITLE
"pull access denied, repository does not exist or may require authorization"

### ISSUE THREAD

**Issue by taotriad** [tinkerbell/operator#18]
When applying the manifest the deployed pod (tinkerbell-operator) fails to pull the image, with the error message:

`Failed to pull image "tinkerbell/operator:v0.1.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/tinkerbell/operator:v0.1.0": failed to resolve reference "docker.io/tinkerbell/operator:v0.1.0": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed`

Do I need to make any special setup before applying this manifest?

**Comment by chrisdoherty4** [comment]
Hi @taotriad. Thanks for checking in to this project. Its currently under early development and considered experimental (really early stages). Images aren't yet published so you'll want to build them locally.

I'm closing the issue, but feel free to continue the conversation.
